/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static view.Remedios.axcdusuari;

/**
 *
 * @author Bruno
 */
public class Metricas extends javax.swing.JInternalFrame {

    public static int axcdusuari;

    /**
     * Creates new form Metricas
     */
    public Metricas(int sdcdusuari) throws ClassNotFoundException {
        axcdusuari = sdcdusuari;
        initComponents();
        carregaTabela();
        jLabel4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        entDsmetrica = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botCadastrar = new javax.swing.JButton();
        botAtualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        entVlinicial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        entVlfinal = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Nome");

        entDsmetrica.setBackground(new java.awt.Color(255, 255, 153));

        jLabel2.setText("Vl. inicial");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Qtde em estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 102));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        botCadastrar.setText("Cadastrar");
        botCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCadastrarActionPerformed(evt);
            }
        });

        botAtualizar.setText("Atualizar");
        botAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAtualizarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("CADASTRO DE METRICAS");

        jLabel4.setText("jLabel4");

        jLabel5.setText("Vl. final");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botCadastrar)
                                    .addComponent(entVlinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botAtualizar)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(entVlfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(entDsmetrica)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel3)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(entDsmetrica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(entVlinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(entVlfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botCadastrar)
                            .addComponent(botAtualizar))
                        .addGap(24, 24, 24)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        Object sdcdmetrica = jTable1.getValueAt(jTable1.getSelectedRow(), 0);
        Object sdnmmetrica = jTable1.getValueAt(jTable1.getSelectedRow(), 1);
        Object sdvlinicial = jTable1.getValueAt(jTable1.getSelectedRow(), 2);
        Object sdvlfinal = jTable1.getValueAt(jTable1.getSelectedRow(), 3);

        String axcdmetrica = sdcdmetrica.toString();
        String axdsmetrica = sdnmmetrica.toString();
        String axvlinicial = sdvlinicial.toString();
        String axvlfinal = sdvlfinal.toString();

        jLabel4.setText(axcdmetrica);
        entDsmetrica.setText(axdsmetrica);
        entVlinicial.setText(axvlinicial);
        entVlfinal.setText(axvlfinal);
    }//GEN-LAST:event_jTable1MouseClicked

    private void botCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCadastrarActionPerformed

        try {
            double finalx = Double.parseDouble(entVlfinal.getText());
            double inicial = Double.parseDouble(entVlinicial.getText());
            if (finalx < inicial) {
                JOptionPane.showMessageDialog(rootPane, "Valor final não pode ser menor que o inicial.");
            } else {
                inserirDados();
                entDsmetrica.setText("");
                entVlinicial.setText("");
                entVlfinal.setText("");
                carregaTabela();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Metricas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Metricas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botCadastrarActionPerformed


    private void botAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAtualizarActionPerformed
        try {
            atualizaDados();
            // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Remedios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botAtualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAtualizar;
    private javax.swing.JButton botCadastrar;
    private javax.swing.JTextField entDsmetrica;
    private javax.swing.JTextField entVlfinal;
    private javax.swing.JTextField entVlinicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
 public void inserirDados() throws SQLException, ClassNotFoundException {
        try {
            //MySql connector driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_renalcontrol?useTimezone=true&serverTimezone=UTC", "root", "root");
            //Comando SQL
            Statement stmt = con.createStatement();
            //Coleta dados do formulário
            String sdnmmetrica = entDsmetrica.getText().trim();
            double sdvlinicial = Double.parseDouble(entVlinicial.getText());
            double sdvlfinal = Double.parseDouble(entVlfinal.getText());
            int sdcdusuari = axcdusuari;

            //Insere dados no banco
            String sddscomsql = " insert into metricas (cdusuari,vlinicial,vlfinal, nmmetrica) values (";
            sddscomsql += sdcdusuari + ", " + sdvlinicial + ", " + sdvlfinal + ", '" + sdnmmetrica + "')";
            stmt.executeUpdate(sddscomsql);
            JOptionPane.showMessageDialog(rootPane, sdnmmetrica + " cadastrado com sucesso.");

        } catch (SQLException Erro) {
            JOptionPane.showMessageDialog(null,
                    "Erro Cmdo SQL" + Erro.getMessage());

// Trata erros de conexão.
        }
    }

    public void atualizaDados() throws ClassNotFoundException {
        try {
            //MySql connector driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_renalcontrol?useTimezone=true&serverTimezone=UTC", "root", "root");
            //Comando SQL
            Statement stmt = con.createStatement();
            //Coleta dados do formulário
            int cdmetrica = Integer.parseInt(jLabel4.getText());
            String sdnmmetrica = entDsmetrica.getText().trim();
            double sdvlinicial = Double.parseDouble(entVlinicial.getText());
            double sdvlfinal = Double.parseDouble(entVlfinal.getText());
            int sdcdusuari = axcdusuari;

            //Insere dados no banco
            String sddscomsql = "update metricas set nmmetrica ='" + sdnmmetrica + "'," + "vlinicial=" + sdvlinicial + ", vlfinal=" + sdvlfinal + " where cdmetrica = " + cdmetrica;
            stmt.executeUpdate(sddscomsql);
            JOptionPane.showMessageDialog(rootPane, sdnmmetrica + " atualizado.");
            carregaTabela();

        } catch (SQLException Erro) {
            JOptionPane.showMessageDialog(null,
                    "Erro Cmdo SQL" + Erro.getMessage());

// Trata erros de conexão.
        }
    }

    public void carregaTabela() throws ClassNotFoundException {
        DefaultTableModel modelo = new DefaultTableModel(null, new String[]{"ID", "Métrica", "Vl.inicial", "Vl.final"});

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_renalcontrol?useTimezone=true&serverTimezone=UTC", "root", "root");
            Statement stmt = con.createStatement();
            ResultSet rs_metrica;
            String sddscomsql = " select * from metricas where metricas.cdusuari = " + axcdusuari;
            rs_metrica = stmt.executeQuery(sddscomsql);
            while (rs_metrica.next() == true) {
                String[] dados = new String[4];
                dados[0] = String.valueOf((int) rs_metrica.getInt("cdmetrica"));
                dados[1] = rs_metrica.getString("nmmetrica");
                dados[2] = String.valueOf(rs_metrica.getDouble("vlinicial"));
                dados[3] = String.valueOf(rs_metrica.getDouble("vlfinal"));
                modelo.addRow(dados);
                jTable1.setModel(modelo);
                jTable1.getColumnModel().getColumn(0).setPreferredWidth(1);
            }
            rs_metrica.close();
        } catch (SQLException Erro) {
            javax.swing.JOptionPane.showMessageDialog(null,
                    "Erro Cmdo SQL" + Erro.getMessage());
        }

    }

}
